---

- name: Network Getting Started First Playbook
  connection: network_cli
  ansible_network_os: nxos
  gather_facts: false
  hosts: all
  tasks:

    - name: Get config for NxOS devices
      nxos_facts:
        gather_subset: all
      when: ansible_network_os == 'nxos'
        
    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
