---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  vars_prompt:
   - name: "Version"
     prompt: "Which version Do you want to install?"
  hosts: all
  tasks:

    - name: Get config for NxOS devices
      nxos_facts:
        gather_subset: all

    - name: Display the config
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
        msg: "{{ Version }}"
