---

- name: Network Getting Started First Playbook
  connection: network_cli
  gather_facts: false
  hosts: all
  tasks:

    - name: Get config for NxOS devices
      ansible_network_os=nxos
      nxos_facts:
        gather_subset: all

    - name: Display the config
      ansible_network_os=nxos
      debug:
        msg: "The hostname is {{ ansible_net_hostname }} and the OS is {{ ansible_net_version }}"
